CREATE DATABASE MailingGroup;

CREATE TABLE SystemUser (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(50) NULL,
	LastName NVARCHAR(50) NULL,
	Password NVARCHAR(max) NOT NULL
)

CREATE TABLE MailingGroup (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name nvarchar(250) NOT NULL,
	SystemUserID INT NOT NULL,

	FOREIGN KEY (SystemUserID) REFERENCES SystemUser(ID)
)

CREATE TABLE Mail (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Address nvarchar(256) NOT NULL,
	MailingGroupID INT NOT NULL

	FOREIGN KEY(MailingGroupID) REFERENCES MailingGroup(ID)
)